### ISSUE TITLE
Migration guide was deleted upstream

### ISSUE THREAD

**Issue by jsma** [wagtail-nest/wagtail-modeladmin#35]
The migration guide was removed in https://github.com/wagtail/wagtail/commit/c363f6dd27ada5d6b5eeeec1628119d6d7ac215d#diff-2ce6c1fd36f0fafaed13c950679ac91d9ae11f56b4f65420b97bd477aec5f533 so the link in the README no longer works. Should that guide be added to this repository?

**Comment by zerolab** [comment]
Good catch, @jsma 

The link can be updated to https://docs.wagtail.org/en/v5.2.3/reference/contrib/modeladmin/migrating_to_snippets.html
