### ISSUE TITLE
Wagtail 6.1 layout issue

### ISSUE THREAD

**Issue by jorenham** [wagtail-nest/wagtail-modeladmin#38]
The `ModelAdmin` listing page is rendered incorrectly:

![image](https://github.com/wagtail-nest/wagtail-modeladmin/assets/6208662/7d66bfa2-6e3f-40ff-b290-ab48c2168597)

With Wagtail 6.0, it looks like this:

![image](https://github.com/wagtail-nest/wagtail-modeladmin/assets/6208662/3081b8da-24df-44c5-8acb-8331a5cc446d)

**Comment by zerolab** [comment]
@laymonage I wonder if this will also be fixed by https://github.com/wagtail/wagtail/pull/11936

**Comment by laymonage** [comment]
@zerolab I think so, yep

**Comment by laymonage** [comment]
Hey @jorenham, thanks for the report – could you try upgrading to Wagtail 6.1.1 and see if the issue persists?

**Comment by jorenham** [comment]
@laymonage That appears to fix it; thanks for the help!
