### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by laymonage** [wagtail-nest/wagtail-modeladmin#4]
At the moment, we cannot publish this on PyPI as `wagtail-modeladmin` because the name is too similar to the old [wagtailmodeladmin](https://pypi.org/project/wagtailmodeladmin/) package.

The current plan is to get the old wagtailmodeladmin package transferred to the [wagtail PyPI organisation](https://pypi.org/org/wagtail) and publish this as a new version of that package,  3.0.0.

We'll need to ask the owner of the old package to transfer it, which should be Andy Babic but he's currently on holiday so we'll do it when he gets back.

In the meantime, we are publishing this repository and people can install it from the repository. We aim to get this sorted before the 5.1 final release.

**Comment by laymonage** [comment]
Update: the wagtailmodeladmin package has been removed from PyPI, and we've registered a new wagtail-modeladmin package name. We should be good to go, and can release it as 1.0.0. We probably should update the app's `label` to `wagtail_modeladmin` instead of `wagtailmodeladmin` for consistency:

https://github.com/wagtail-nest/wagtail-modeladmin/blob/ce758e1da4681c766b541ccb3bbd697dd3df7120/wagtail_modeladmin/apps.py#L7

**Comment by laymonage** [comment]
v1.0.0 is released! 🥳

https://pypi.org/project/wagtail-modeladmin/

**Comment by lb-** [comment]
Awesome stuff @laymonage !!
