### ISSUE TITLE
Enhancement: Ability to register ModelAdmin in Reports section

### ISSUE THREAD

**Issue by Swojak-A** [wagtail-nest/wagtail-modeladmin#42]
I've noticed that you can register ModelAdmin MenuItem to Settings menu via `add_to_settings_menu` declaration:
```python
class EmailAdmin(ModelAdmin):
    model = Email
    menu_label = _("Emails")
    add_to_settings_menu = True
    ...
```

However you **can not** do the same to add the ModelAdmin to Reports menu.

**Comment by laymonage** [comment]
Thank you, but this package is on maintenance mode and will not be receiving new features.

If you use the built-in [`ModelViewSet`](https://docs.wagtail.org/en/stable/extending/generic_views.html#modelviewset) instead, it should be possible to do this by setting [the `menu_hook` property](https://docs.wagtail.org/en/stable/reference/viewsets.html#wagtail.admin.viewsets.base.ViewSet.menu_hook) on the viewset class to `"register_reports_menu_item"`.
